Started fedora-messaging integration
fedora-infra/noggin pull request #146
Opened 2020-02-27 12:58 UTC by ryanlerch

Signed-off-by: Ryan Lerch <rlerch@redhat.com>

2020-02-27 13:02 UTC, ryanlerch commented on securitas/controller/group.py
> +        msg = schema.MemberSponsorV1()
When trying to use my schema here, this fails with the message:

    TypeError: The class <class 'securitas.messaging.schema.MemberSponsorV1'> is not in the message registry, which indicates it is not in the current list of entry points for "fedora_messaging". Please check that the class has been added to your package's entry points.

This bit i added in the pyproject.toml was me trying to add it to the entry points, but it doenst seem to be wokring:

    [tool.poetry.plugins."fedora.messages"]
    "fas.group.member.sponsor.v1"="securitas.messaging.schema:MemberSponsorV1"

2020-02-27 13:04 UTC, ryanlerch commented on securitas/controller/group.py
> +        api.publish(api.Message(topic="hello", body={"Hello": "world!"}))
if you comment out using the schema above, this message goes through to the queue when adding a new user to a group.

to view this message when  it comes in, use `fedora_messaging consume` and have ti running when messages are sent and they will print on the terminal for you

2020-02-27 13:04 UTC, ryanlerch commented on securitas/messaging/schema.py
> +class MemberSponsorV1(message.Message):
I think this is right, just cant test it because of the entry points issue above

2020-02-27 13:05 UTC, ryanlerch commented on devel/ansible/roles/dev/defaults/main.yml
> +rabbitmq_cluster_file_limit: 500000
all these changes to the vagrant box are to install rabbitmq.

2020-02-27 13:09 UTC, ryanlerch commented on devel/ansible/roles/dev/tasks/rabbitmq.yml
> +- name: Override rabbitmq hostname
without this, we get an error like

    Feb 27 08:36:05 ipa.example.com rabbitmq-server[13914]: ERROR: epmd error for host ipa: address (cannot connect to host/port)

when trying to start rabbitmq

2020-02-27 13:11 UTC, ryanlerch commented on pyproject.toml
> +[tool.poetry.plugins."fedora.messages"]
trying to add entry_points for the schema here. does it work? nope.

2020-02-27 16:45 UTC, abompard commented
Here is the test file that I made:
```python
from fedora_messaging import api, config
from securitas.messaging import schema

config.conf.setup_logging()
msg = schema.MemberSponsorV1()
api.publish(api.Message(topic="hello", body={"Hello": "world!"}))
```

Now when I run:
```
$ poetry run python testmsg.py 
[INFO fedora_messaging.message] Registering the 'fas.group.member.sponsor.v1' key as the '<class 'securitas.messaging.schema.MemberSponsorV1'>' class in the Message class registry
[INFO fedora_messaging.message] Registering the 'base.message' key as the '<class 'fedora_messaging.message.Message'>' class in the Message class registry
[INFO twisted] Log opened.
[INFO twisted] Starting factory FedoraMessagingFactoryV2(parameters=<URLParameters host=localhost port=5672 virtual_host=/ ssl=False>, confirms=True)
[INFO fedora_messaging.twisted.protocol] Waiting for 0 consumer(s) to finish processing before halting
[INFO fedora_messaging.twisted.protocol] Finished canceling 0 consumers
[INFO fedora_messaging.twisted.protocol] Disconnect requested, but AMQP connection already gone
```

And if I have a `fedora-messaging consume` command opened on the side it does get the message. It also seems to work when I use the message class you wrote (and I add the `msg` property which is set as required).

So, something else in your setup is breaking things maybe?

2020-02-27 20:51 UTC, ryanlerch commented
> Here is the test file that I made:
> 
> ```python
> from fedora_messaging import api, config
> from securitas.messaging import schema
> 
> config.conf.setup_logging()
> msg = schema.MemberSponsorV1()
> api.publish(api.Message(topic="hello", body={"Hello": "world!"}))
> ```
> 
> Now when I run:
> 
> ```
> $ poetry run python testmsg.py 
> [INFO fedora_messaging.message] Registering the 'fas.group.member.sponsor.v1' key as the '<class 'securitas.messaging.schema.MemberSponsorV1'>' class in the Message class registry
> [INFO fedora_messaging.message] Registering the 'base.message' key as the '<class 'fedora_messaging.message.Message'>' class in the Message class registry
> [INFO twisted] Log opened.
> [INFO twisted] Starting factory FedoraMessagingFactoryV2(parameters=<URLParameters host=localhost port=5672 virtual_host=/ ssl=False>, confirms=True)
> [INFO fedora_messaging.twisted.protocol] Waiting for 0 consumer(s) to finish processing before halting
> [INFO fedora_messaging.twisted.protocol] Finished canceling 0 consumers
> [INFO fedora_messaging.twisted.protocol] Disconnect requested, but AMQP connection already gone
> ```
> 
> And if I have a `fedora-messaging consume` command opened on the side it does get the message. It also seems to work when I use the message class you wrote (and I add the `msg` property which is set as required).
> 
> So, something else in your setup is breaking things maybe?

Hmm, when i run that script it seems to work now too... just when running it from within securitas it seems to fail...

2020-02-28 03:42 UTC, abompard commented
I tied sponsoring a member into a group from the UI, and it did send the message.

2020-02-28 11:37 UTC, abompard requested changes
The main change that is also necessary is that message schemas actually need to be in their own python packages, so apps that listen to them can install the package and not the whole of securitas...
So I would recommend actually making a separate repo in Github called securitas-messages (to be renamed later :'-(  ), with its own `pyproject.toml` file, etc, and add it to the securitas dependencies.
I'm going to jumpstart that repo for you.

Here it is: https://github.com/fedora-infra/securitas-messages. You should have write access to it.

2020-02-28 11:37 UTC, abompard commented on devel/ansible/roles/dev/tasks/rabbitmq.yml
> +- name: Override rabbitmq hostname
It worked without this step for me. Can you try again and if it fails again maybe we can debug it together?

2020-02-28 11:37 UTC, abompard commented on securitas/utility/messaging.py
> +    except (fml_exceptions.ConnectionException, fml_exceptions.PublishReturned) as e:
Here I think you can simply catch `fml_exceptions.BaseException`, because you want the message to be logged whether it's a temporary error or not.

2020-02-28 11:37 UTC, abompard commented on securitas/utility/messaging.py
> +    app.logger.error(f"Publishing message failed. Retrying. {traceback.format_tb(sys.exc_info()[2])}")
I think this can be a warning-level log.

2020-02-28 11:37 UTC, abompard commented on securitas/utility/messaging.py
> +from securitas import app
I would recommend using `from flask import current_app` instead, it can help solve circular imports.

2020-02-28 11:37 UTC, abompard commented on securitas/utility/messaging.py
> +import backoff
The `import X` lines usually go before the `from X import Y` lines.

2020-02-28 11:37 UTC, abompard commented on securitas/utility/messaging.py
> +        app.logger.error(f"Publishing message failed. Giving up. {traceback.format_tb(sys.exc_info()[2])}")
I think you can use `app.logger.exception`, it'll log the traceback automatically.

2020-02-28 11:37 UTC, abompard commented on securitas/utility/messaging.py
> +    (fml_exceptions.ConnectionException, fml_exceptions.PublishReturned),
Please replace `PublishReturned` with `PublishException` (see [bodhi commit a3ff73](https://github.com/fedora-infra/bodhi/commit/a3ff73d0c57236cd1d9d38d967c029b7d2b6f435))

2020-02-28 11:37 UTC, abompard commented on pyproject.toml
> +"fas.group.member.sponsor.v1"="securitas.messaging.schema:MemberSponsorV1"
I would recommend prefixing with `securitas` as it's not related to the topic but to the app.

2020-03-02 12:30 UTC, ryanlerch commented
Okay, moved the schema to the separate repo, and added it as a git dep in poetry.

Also have added tests to keep the coverage at 100%.

2020-03-03 10:25 UTC, ryanlerch commented
@abompard any thoughts on why this is failing liccheck? is it because i am pulling in securitas-messages with git?

2020-03-03 10:29 UTC, abompard commented
I think you need to add `GPLv2+` to the allowed licenses in `pyproject.toml`. It also looks like liccheck can't find the license for `securitas-messages`.

2020-03-09 11:23 UTC, abompard approved these changes
Yeah, I think it's good now :-)

2020-03-09 11:47 UTC, merged