remove redirect from user settings edit
fedora-infra/noggin pull request #175
Opened 2020-03-26 10:49 UTC by ryanlerch

previously, when editng the user settings (profile or gpg keys)
after a successful POST, noggin would redirect back to the profile
page, rather than to the settings page like with other settings pages
like OTP. This changes noggin to return to the settings edit form
rather than the profile page

Signed-off-by: Ryan Lerch <rlerch@redhat.com>

2020-03-26 11:27 UTC, abompard commented
I think that on POST success it should still do a redirect, even if it is to the same page. Otherwise when trying to reload the page users will have the browser's warning message about sending the request again.
In my understanding the only situation where POST should not end up in a redirect is when there is an error with the posted data (in which case it should ideally never end up in a redirect but sometimes that makes things very complicated so we do it sometimes).

2020-03-27 02:17 UTC, ryanlerch commented
Thanks @abompard have updated with changes

2020-03-27 07:46 UTC, abompard requested changes

2020-03-27 07:46 UTC, abompard commented on noggin/controller/user.py
> -            return result
If you're not returning the redirect that `_user_mod` returned, then is it still redirecting?

2020-03-27 07:46 UTC, abompard commented on noggin/controller/user.py
> -            return result
Same question here.

2020-03-27 07:46 UTC, abompard commented on noggin/tests/unit/controller/test_user.py
> +        redirect=False,
If the POST is successful, then it should redirect, no?

2020-03-27 07:46 UTC, abompard commented on noggin/tests/unit/controller/test_user.py
> +    assert result.status_code == 200
Same thing here, if the POST is successful, it should redirect.

2020-03-27 07:46 UTC, abompard commented on noggin/tests/unit/controller/test_user.py
> +        redirect=False,
Same here.

2020-03-27 07:46 UTC, abompard commented on noggin/tests/unit/controller/test_user.py
> +    assert result.status_code == 200
And same here. Unless I'm missing something?

2020-03-27 07:46 UTC, abompard commented on noggin/tests/unit/utilities.py
> +    response, expected_url, expected_message, expected_category, redirect=True
I haven't seen a case where there should be no redirect.

2020-03-30 12:27 UTC, abompard approved these changes
LGTM, thanks!

2020-03-30 13:06 UTC, merged