Add for="" property to BooleanField labels
fedora-infra/noggin pull request #660
Opened 2021-06-06 14:26 UTC by jaller94

This is just a guess of what might needs to be done to fix #658.

Someone with a working development environment should verify this change.

2021-06-28 09:34 UTC, abompard requested changes
Just one minor comment. Also, please use `-s` when committing to add a "signoff" line to the commit message.

Thanks!

2021-06-28 09:34 UTC, abompard commented on noggin/templates/_form_macros.html
> +    <label class="form-check-label ml-1" {% if field.id %}for="{{ field.id }}"{% endif %}><strong>{{ field.label.text }}</strong></label>
I don't think you need the test here, fields of forms built with WTForms always have an ID.

2021-06-28 11:45 UTC, jaller94 commented
Hi @abompard, I don't have more time to spend on this.
I was just looking to make a reasonable, quick suggestion of how the issue I found might get fixed.

Feel free to take my change, re-commit or change it. No need for this PR/branch to get merged, if it's not compliant with the repo's license.

2021-06-28 12:55 UTC, abompard commented
Sure, thanks @jaller94.

2021-06-29 09:00 UTC, abompard commented
Superseded by 81d38e4.

2021-06-29 09:00 UTC, closed without merging