add the basic FAS theme
fedora-infra/noggin pull request #98
Opened 2020-02-04 01:33 UTC by ryanlerch

This adds a new theme, FAS for use with the Fedora Account System

Signed-off-by: Ryan Lerch <rlerch@redhat.com>

2020-02-04 02:53 UTC, ryanlerch commented
Added another commit which adds a macro to the theme allowing a theme to specify an element to use for changing a group's details.

Resolves: #46 #47

2020-02-04 13:50 UTC, abompard requested changes
One more thing: the "Add user" input on the group page is back to having joined borders with the users list.

2020-02-04 13:50 UTC, abompard commented on securitas/themes/fas/templates/main.html
> +                request change of details
Maybe capitalize this?

2020-02-05 02:02 UTC, ryanlerch commented on securitas/themes/fas/templates/main.html
> +    {% if current_user_is_sponsor and sponsor_form %}
i was just using the same logic we used for actually showing the add user box to sponsors of a group:

https://github.com/fedora-infra/securitas/blob/ea49362a00688a4dd15cd19cb8cf74be2885d43a/securitas/templates/group.html#L44

2020-02-05 03:34 UTC, ryanlerch commented
> One more thing: the "Add user" input on the group page is back to having joined borders with the users list.

fixed this one too

2020-02-05 07:37 UTC, abompard approved these changes
Looks good, thanks!

2020-02-05 09:09 UTC, merged